const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

const LOCAL_CHAIN_IDS = new Set([1337, 31337]);
const ORDER_CREATION_FEE_UNITS = "1";
const TOKEN_DISTRIBUTION_UNITS = "50000";
const DEPLOY_GAS_LIMIT = 15_000_000;
const ERC20_TX_GAS_LIMIT = 500_000;

function ensureLocalhostNetwork(networkName, chainId) {
  if (networkName === "hardhat") {
    throw new Error(
      "This script must target a persistent node. Start `npx hardhat node` and run with `--network localhost`."
    );
  }

  if (!LOCAL_CHAIN_IDS.has(Number(chainId))) {
    throw new Error(`Refusing to run on non-local chainId ${chainId}.`);
  }
}

function writeJson(filePath, payload) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, JSON.stringify(payload, null, 2) + "\n", "utf8");
}

function tryWriteFile(filePath, content) {
  try {
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    fs.writeFileSync(filePath, content, "utf8");
    return true;
  } catch (error) {
    console.warn(`Could not write ${filePath}: ${error.message}`);
    return false;
  }
}

async function deployToken(name, symbol) {
  const TestToken = await hre.ethers.getContractFactory("TestToken");
  const token = await TestToken.deploy(name, symbol, { gasLimit: DEPLOY_GAS_LIMIT });
  await token.waitForDeployment();
  return token;
}

async function main() {
  const [deployer, maker, taker] = await hre.ethers.getSigners();
  const { chainId } = await hre.ethers.provider.getNetwork();

  ensureLocalhostNetwork(hre.network.name, chainId);

  console.log(`Network: ${hre.network.name} (${chainId})`);
  console.log(`Deployer: ${deployer.address}`);

  const feeToken = await deployToken("Local Fee Token", "LFT");
  const tokenA = await deployToken("Local Token A", "LTKA");
  const tokenB = await deployToken("Local Token B", "LTKB");

  const feeTokenAddress = await feeToken.getAddress();
  const tokenAAddress = await tokenA.getAddress();
  const tokenBAddress = await tokenB.getAddress();
  const orderFee = hre.ethers.parseUnits(ORDER_CREATION_FEE_UNITS, 18);
  const distributionAmount = hre.ethers.parseUnits(TOKEN_DISTRIBUTION_UNITS, 18);

  const allowedTokens = [feeTokenAddress, tokenAAddress, tokenBAddress];
  const OTCSwap = await hre.ethers.getContractFactory("OTCSwap");
  const otcSwap = await OTCSwap.deploy(feeTokenAddress, orderFee, allowedTokens, {
    gasLimit: DEPLOY_GAS_LIMIT
  });
  await otcSwap.waitForDeployment();
  const otcSwapAddress = await otcSwap.getAddress();

  for (const recipient of [maker, taker]) {
    await (await feeToken.transfer(recipient.address, distributionAmount, { gasLimit: ERC20_TX_GAS_LIMIT })).wait();
    await (await tokenA.transfer(recipient.address, distributionAmount, { gasLimit: ERC20_TX_GAS_LIMIT })).wait();
    await (await tokenB.transfer(recipient.address, distributionAmount, { gasLimit: ERC20_TX_GAS_LIMIT })).wait();
  }

  const deployment = {
    generatedAt: new Date().toISOString(),
    network: {
      name: hre.network.name,
      chainId: Number(chainId),
    },
    deployer: deployer.address,
    orderCreationFee: ORDER_CREATION_FEE_UNITS,
    orderCreationFeeWei: orderFee.toString(),
    contracts: {
      otcSwap: otcSwapAddress,
      feeToken: feeTokenAddress,
      tokenA: tokenAAddress,
      tokenB: tokenBAddress,
      allowedTokens,
    },
    fundedAccounts: {
      maker: maker.address,
      taker: taker.address,
      amountPerToken: TOKEN_DISTRIBUTION_UNITS,
    },
  };

  const localDeploymentPath = path.join(__dirname, "..", "deployments", "local.json");
  writeJson(localDeploymentPath, deployment);
  console.log(`Wrote deployment details: ${localDeploymentPath}`);

  const uiRoot = path.join(__dirname, "..", "..", "whaleswap-ui");
  const uiDeploymentModulePath = path.join(uiRoot, "js", "local-dev.deployment.js");
  const deploymentModule = `// Auto-generated by whaleswap-contract/scripts/deploy.local.js\n` +
    `export const localDeployment = ${JSON.stringify(deployment, null, 2)};\n`;
  if (tryWriteFile(uiDeploymentModulePath, deploymentModule)) {
    console.log(`Updated UI local deployment module: ${uiDeploymentModulePath}`);
  }

  const artifactPath = path.join(
    __dirname,
    "..",
    "artifacts",
    "contracts",
    "OTCSwap.sol",
    "OTCSwap.json"
  );
  if (fs.existsSync(artifactPath)) {
    const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));
    const uiAbiPath = path.join(uiRoot, "js", "abi", "OTCSwap.js");
    const abiModule = `// Auto-generated by whaleswap-contract/scripts/deploy.local.js\n` +
      `export const abi = ${JSON.stringify(artifact.abi, null, 2)};\n`;
    if (tryWriteFile(uiAbiPath, abiModule)) {
      console.log(`Synced UI ABI: ${uiAbiPath}`);
    }
  } else {
    console.warn(`Artifact not found, skipped ABI sync: ${artifactPath}`);
  }

  console.log("\nLocal deployment complete:");
  console.log(`OTCSwap:  ${otcSwapAddress}`);
  console.log(`Fee token: ${feeTokenAddress} (LFT)`);
  console.log(`Token A:   ${tokenAAddress} (LTKA)`);
  console.log(`Token B:   ${tokenBAddress} (LTKB)`);
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
